# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Lucky7"
license = "MIT"
licenselink = "https://github.com/ooorange777/hugo-theme-lucky7/blob/master/LICENSE"
description = "A simple GoHugo Theme for personal blog."
homepage = "http://github.com/ooorange777/hugo-theme-lucky7/"
tags = ["simple", "hugo", "blog"]
features = []
min_version = "0.1.0"

[author]
  name = "ooorange777"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
